server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: circuit-breaker # rama de la cual el config service debe ingresar
          uri: https://github.com/Equi00/microservicios-java # repositorio al cual debe ingresar
          search-paths: config-data # los datos de los puertos de cada servicio
  application:
    name: config-service
